### PR TITLE
XRT-1921: Changed from global TSM invoke ID cache to a per device cache

### PR DESCRIPTION
**Pull request by FraserG01**
The example apps and simulator code will not be moved to use this new invoke method. The reason being is it requires linking against the BACnet device service to work.

Any future development on the simulator will be made on an v1.0-sim-branch

### CODE REVIEW

**Review by dpazj — CHANGES_REQUESTED** [review]
- I've noticed there is sometimes no null check for the result of get_tsm_device(). Either add a null check for this on each use, or modify the tsm_ functions to handle NULL tsm_devices.
- Have spoken about adding in our own data structure for get_tsm_device instead of coupling with the device service.

**Comment by FraserG01** [comment]
@SteveOss 

@dpazj  has pointed out that linking the get_tsm_device function from the device service may actually be in breach of the BACnet stack license where any changes to the source must be provided publicly. He also has concerns about the stack being dependent on the device service to work.

He has found a hash map implementation that could be integrated into the stack instead:
https://github.com/tidwall/hashmap.c

What do you think?

**Comment by dpazj** [comment]
Just to add, there may be other data structures that are better for this specific use-case. Probably worth some investigation.

**Comment by SteveOss** [comment]
@FraserG01 The bacnet stack repo is public so all our changes are available. Don't want to maintain a second hash map or take the additional size overhead.

**Comment by FraserG01** [comment]
> @FraserG01 The bacnet stack repo is public so all our changes are available. Don't want to maintain a second hash map or take the additional size overhead.

@SteveOss 

get_tsm_device is extern though
extern tsm_device_t *get_tsm_device(BACNET_ADDRESS *address);

where the actual contents are in the device service

**Comment by SteveOss** [comment]
@FraserG01 Yep this code isn't part of the stack. Copyright explicitly says can be linked with external code without copyright implications for external code.

**Comment by FraserG01** [comment]
> @FraserG01 Yep this code isn't part of the stack. Copyright explicitly says can be linked with external code without copyright implications for external code.

@SteveOss ah right okay, so do you think the current way of approaching this is the best way?

**Comment by SteveOss** [comment]
@FraserG01 Yes

**Review by dpazj — APPROVED** [review]
LGTM

**Pull request merged**
