### PR TITLE
XRT-1780 branch

### PR DESCRIPTION
**Pull request by SteveOss**
RISCV build support added

### CODE REVIEW

**Comment by SteveOss** [comment]
Have tagged repo with v1.0.8 (used by packager). Should re-tag on merge.

**Review by FraserG01 — CHANGES_REQUESTED** [review]
LGTM

**Review by FraserG01 — APPROVED** [review]
LGTM

**Comment by FraserG01** [comment]
@SteveOss accidentally hit request changes, have approved now

**Pull request merged**
