### PR TITLE
XRT-1461:  Added ability to change the Vendor Name

### PR DESCRIPTION
**Pull request by FraserG01**

### CODE REVIEW

**Review by SteveOss — CHANGES_REQUESTED** [review]
For set vendor name function, would assume name is a string, so can get length via strlen, length argument is redundant IMHO.

**Comment by FraserG01** [comment]
> For set vendor name function, would assume name is a string, so can get length via strlen, length argument is redundant IMHO.

@SteveOss was just following how the other stack functions do it, should I change those as well?

**Comment by SteveOss** [comment]
@FraserG01 Sometimes (like when you get a message from MQTT as a char*) there may not be a zero terminator with a string, in this case the form with a char * and length is required. However if a function is always used with a zero terminated C string then the former is better, so might make sense to migrate functions as long as are sure is only ever used with a C string.

**Comment by FraserG01** [comment]
> @FraserG01 Sometimes (like when you get a message from MQTT as a char*) there may not be a zero terminator with a string, in this case the form with a char * and length is required. However if a function is always used with a zero terminated C string then the former is better, so might make sense to migrate functions as long as are sure is only ever used with a C string.

@SteveOss Not sure how safe it will be as there is cases where we store the string in a char array and have the length separate

typedef struct BACnet_Character_String {
    size_t length;
    uint8_t encoding;
    /* limit - 6 octets is the most our tag and type could be */
    char value[MAX_CHARACTER_STRING_BYTES];
} BACNET_CHARACTER_STRING;


        case PROP_LOCATION:
            status = WPValidateString(&value, MAX_DEV_LOC_LEN, true,
                &wp_data->error_class, &wp_data->error_code);
            if (status) {
                Device_Set_Location(                                                 // An example setting location via a request from another device
                    characterstring_value(&value.type.Character_String),
                    characterstring_length(&value.type.Character_String));
            }


where the length is taken from:


```
size_t characterstring_length(BACNET_CHARACTER_STRING *char_string)
{
    size_t length = 0;

    if (char_string) {
        length = char_string->length;

        /* Length within bounds? */
        if (length > CHARACTER_STRING_CAPACITY) {
            length = CHARACTER_STRING_CAPACITY;
        }
    }

    return length;
}
```

**Review by SteveOss — APPROVED** [review]
OK, lets leave with safer form

**Pull request merged**
